import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Base Enterprise Dark Foundation
        brand: {
          bg: "var(--brand-bg)",
          surface: "var(--brand-surface)",
          elevated: "var(--brand-elevated)",
          card: "var(--brand-card)",
          border: "var(--brand-border)",
          borderSubtle: "var(--brand-border-subtle)",
          borderStrong: "var(--brand-border-strong)",
          text: "var(--brand-text)",
          muted: "var(--brand-muted)",
          subtle: "var(--brand-subtle)",
        },
        navy: "var(--navy)",
        ink: "var(--ink)",
        muted: "var(--muted)",
        subtle: "var(--subtle)",
        line: "var(--line)",
        lineStrong: "var(--line-strong)",
        surface: "var(--surface)",
        surfaceAlt: "var(--bg-alt)",
        appBg: "var(--bg)",
        upay: {
          DEFAULT: "#F59E0B",
          gold: "#F59E0B",
          amber: "#D97706",
          navy: "#0B132B",
          dark: "#080E1A",
          cyan: "#0EA5E9",
          emerald: "#10B981",
          soft: "rgba(245, 158, 11, 0.12)",
          light: "#FDE68A",
        },
        risk: {
          critical: "#EF4444",
          criticalSoft: "rgba(239, 68, 68, 0.12)",
          high: "#F97316",
          highSoft: "rgba(249, 115, 22, 0.12)",
          medium: "#F59E0B",
          mediumSoft: "rgba(245, 158, 11, 0.12)",
          low: "#10B981",
          lowSoft: "rgba(16, 185, 129, 0.12)",
          info: "#3B82F6",
          infoSoft: "rgba(59, 130, 246, 0.12)",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "ui-monospace", "monospace"],
      },
      boxShadow: {
        card: "0 1px 3px rgba(0, 0, 0, 0.35)",
        panel: "0 1px 4px rgba(0, 0, 0, 0.4), 0 0 0 1px #252D37",
        elevated: "0 6px 20px rgba(0, 0, 0, 0.5), 0 0 0 1px #252D37",
        modal: "0 24px 48px rgba(0, 0, 0, 0.75), 0 0 0 1px #252D37",
        drawer: "-8px 0 32px rgba(0, 0, 0, 0.7), 0 0 0 1px #252D37",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        DEFAULT: "8px",
        md: "10px",
        lg: "12px",
        xl: "14px",
      },
    },
  },
  plugins: [],
} satisfies Config;
