services:
  - type: web
    name: upay-sentinel
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 3000
