import {
  Transaction,
  InvestigationCase,
  TimelineEvent,
  NetworkNode,
  NetworkEdge,
  CustomerProfile,
  AlertItem,
  ChatMessage,
  RiskFactor,
} from "@/types";

export const initialTransactions: Transaction[] = [
  {
    id: "TXN-8F42",
    customer: "U-1042",
    recipient: "U-8831",
    amount: 48500,
    time: "02:13 AM",
    timestamp: Date.now() - 2 * 60 * 1000,
    type: "Wallet Transfer",
    device: "DEV-8821",
    isNewDevice: true,
    location: "Dhaka",
    isNewLocation: false,
    riskLevel: "Critical",
    riskScore: 94,
    status: "Investigating",
    flags: [
      "Amount 4.8× above normal baseline",
      "Unrecognized device DEV-8821",
      "Off-hours transaction (02:13 AM)",
      "Recipient linked to mule cluster #17",
      "6 transactions within 8 minutes",
    ],
  },
  {
    id: "TXN-92KD",
    customer: "U-2214",
    recipient: "U-9210",
    amount: 32000,
    time: "01:48 AM",
    timestamp: Date.now() - 8 * 60 * 1000,
    type: "Cash Out",
    device: "DEV-1049",
    isNewDevice: false,
    location: "Chattogram",
    isNewLocation: true,
    riskLevel: "High",
    riskScore: 87,
    status: "Flagged",
    flags: ["Rapid velocity cash-out", "Unusual location: Chattogram", "High single transaction value"],
  },
  {
    id: "TXN-37LM",
    customer: "U-4421",
    recipient: "U-4412",
    amount: 76200,
    time: "12:56 AM",
    timestamp: Date.now() - 14 * 60 * 1000,
    type: "Wallet Transfer",
    device: "DEV-4402",
    isNewDevice: true,
    location: "Sylhet",
    isNewLocation: true,
    riskLevel: "High",
    riskScore: 89,
    status: "Flagged",
    flags: ["High value transfer", "Brand new recipient wallet", "Geographic jump in 45 min"],
  },
  {
    id: "TXN-71QA",
    customer: "U-8821",
    recipient: "U-1120",
    amount: 8200,
    time: "11:24 PM",
    timestamp: Date.now() - 45 * 60 * 1000,
    type: "Wallet Transfer",
    device: "DEV-7721",
    isNewDevice: false,
    location: "Dhaka",
    isNewLocation: false,
    riskLevel: "Medium",
    riskScore: 61,
    status: "Monitoring",
    flags: ["Velocity spike: 4 transfers in 1 hour"],
  },
  {
    id: "TXN-11BT",
    customer: "U-2910",
    recipient: "U-5512",
    amount: 2450,
    time: "10:42 PM",
    timestamp: Date.now() - 65 * 60 * 1000,
    type: "Merchant Pay",
    device: "DEV-2910",
    isNewDevice: false,
    location: "Dhaka",
    isNewLocation: false,
    riskLevel: "Low",
    riskScore: 18,
    status: "Approved",
    flags: ["Verified merchant checkout", "Within historical spending envelope"],
  },
  {
    id: "TXN-40PX",
    customer: "U-7712",
    recipient: "U-8339",
    amount: 12800,
    time: "10:18 PM",
    timestamp: Date.now() - 95 * 60 * 1000,
    type: "Cash Out",
    device: "DEV-7712",
    isNewDevice: false,
    location: "Khulna",
    isNewLocation: false,
    riskLevel: "Medium",
    riskScore: 58,
    status: "Monitoring",
    flags: ["Higher than 7-day median cash out"],
  },
  {
    id: "TXN-29WV",
    customer: "U-5520",
    recipient: "U-9821",
    amount: 1200,
    time: "09:51 PM",
    timestamp: Date.now() - 130 * 60 * 1000,
    type: "Wallet Transfer",
    device: "DEV-5520",
    isNewDevice: false,
    location: "Rajshahi",
    isNewLocation: false,
    riskLevel: "Low",
    riskScore: 12,
    status: "Approved",
    flags: ["Recurring peer-to-peer contact", "Low transaction risk score"],
  },
  {
    id: "TXN-64KL",
    customer: "U-6120",
    recipient: "M-4012",
    amount: 450,
    time: "09:30 PM",
    timestamp: Date.now() - 150 * 60 * 1000,
    type: "Mobile Recharge",
    device: "DEV-6120",
    isNewDevice: false,
    location: "Dhaka",
    isNewLocation: false,
    riskLevel: "Low",
    riskScore: 8,
    status: "Approved",
    flags: ["Standard airtime recharge"],
  },
  {
    id: "TXN-55ZA",
    customer: "U-3301",
    recipient: "U-4412",
    amount: 65000,
    time: "09:12 PM",
    timestamp: Date.now() - 180 * 60 * 1000,
    type: "Wallet Transfer",
    device: "DEV-8821",
    isNewDevice: true,
    location: "Dhaka",
    isNewLocation: false,
    riskLevel: "Critical",
    riskScore: 91,
    status: "Investigating",
    flags: ["Shared high-risk device DEV-8821", "Mule hub target wallet U-4412"],
  },
  // Expanded Dataset Entries:
  {
    id: "TXN-99XB",
    customer: "U-9182",
    recipient: "U-9901",
    amount: 98000,
    time: "03:45 AM",
    timestamp: Date.now() - 4 * 60 * 1000,
    type: "Wallet Transfer",
    device: "DEV-9901",
    isNewDevice: true,
    location: "Sylhet",
    isNewLocation: true,
    riskLevel: "Critical",
    riskScore: 98,
    status: "Investigating",
    flags: ["Sim swap detected", "Max limit transfer", "Unrecognized IP address"],
  },
  {
    id: "TXN-11CA",
    customer: "U-1283",
    recipient: "M-5501",
    amount: 45000,
    time: "08:15 PM",
    timestamp: Date.now() - 300 * 60 * 1000,
    type: "Merchant Pay",
    device: "DEV-1283",
    isNewDevice: false,
    location: "Dhaka",
    isNewLocation: false,
    riskLevel: "Medium",
    riskScore: 65,
    status: "Flagged",
    flags: ["Unusual merchant category", "Spike in evening volume"],
  }
];

export const riskFactorsTXN8F42: RiskFactor[] = [
  {
    name: "Transaction Amount",
    score: 92,
    weight: 0.25,
    description: "Amount (৳48,500) is 4.8× above the customer's 30-day baseline median of ৳6,800.",
    deviated: true,
  },
  {
    name: "Transaction Velocity",
    score: 84,
    weight: 0.2,
    description: "6 outgoing transfers executed within 8 minutes. Normal velocity is 1 transfer / 2 days.",
    deviated: true,
  },
  {
    name: "Device Anomaly",
    score: 78,
    weight: 0.15,
    description: "Device DEV-8821 first observed 12 minutes before transaction. Zero historical link to U-1042.",
    deviated: true,
  },
  {
    name: "Recipient Risk",
    score: 91,
    weight: 0.2,
    description: "Recipient wallet U-8831 is an intermediary conduit linked to 4 flagged accounts.",
    deviated: true,
  },
  {
    name: "Location Anomaly",
    score: 63,
    weight: 0.1,
    description: "IP geolocated to Mirpur, Dhaka while prior session 40 minutes earlier was in Gulshan, Dhaka.",
    deviated: false,
  },
  {
    name: "Time Anomaly",
    score: 74,
    weight: 0.1,
    description: "Executed at 02:13 AM. User has 0 recorded transactions between 11:30 PM and 7:00 AM.",
    deviated: true,
  },
];

export const investigationCases: InvestigationCase[] = [
  {
    id: "INV-1042",
    riskLevel: "Critical",
    customer: "U-1042",
    amount: 48500,
    reason: "Mule network & Account Takeover",
    analyst: "Arman Hossen",
    status: "Investigating",
    updated: "2 min ago",
    createdTime: "Today at 02:18 AM",
    exposure: 184000,
    transactionsCount: 27,
    networkConnections: 12,
    riskScore: 94,
    summary:
      "Customer U-1042 performed an unusually large transfer of ৳48,500 from a newly registered device DEV-8821 at 02:13 AM. The recipient U-8831 is connected to previously flagged transaction cluster #17. Multi-signal analysis indicates high probability of account takeover and illicit fund dispersal.",
    recommendation:
      "Freeze pending outgoing transfers to U-8831, initiate immediate biometric/OTP step-up verification on U-1042 primary device, and subpoena linked recipient wallets.",
    confidence: 96,
  },
  {
    id: "INV-1038",
    riskLevel: "High",
    customer: "U-2214",
    amount: 32000,
    reason: "Account takeover & sudden cash-out",
    analyst: "Sara Rahman",
    status: "Pending Review",
    updated: "18 min ago",
    createdTime: "Today at 01:52 AM",
    exposure: 64000,
    transactionsCount: 14,
    networkConnections: 6,
    riskScore: 87,
    summary:
      "Customer U-2214 had their PIN reset via USSD followed immediately by full balance cash-out at an agent in Chattogram. Customer has lived in Sylhet for past 2 years.",
    recommendation: "Hold agent settlement and reach out to registered SIM owner.",
    confidence: 89,
  },
  {
    id: "INV-1031",
    riskLevel: "High",
    customer: "U-4421",
    amount: 76200,
    reason: "Suspicious recipient & rapid layering",
    analyst: "Nadia Islam",
    status: "Investigating",
    updated: "42 min ago",
    createdTime: "Yesterday at 11:45 PM",
    exposure: 215000,
    transactionsCount: 38,
    networkConnections: 19,
    riskScore: 89,
    summary:
      "Wallet received multiple small deposits from 8 distinct accounts within 1 hour, immediately aggregating into a single ৳76,200 transfer to high-risk wallet U-4412.",
    recommendation: "Flag source wallets for smurfing / micro-structuring indicators.",
    confidence: 92,
  },
  {
    id: "INV-1028",
    riskLevel: "Medium",
    customer: "U-8821",
    amount: 8200,
    reason: "Abnormal transaction velocity",
    analyst: "Arman Hossen",
    status: "Monitoring",
    updated: "1 hr ago",
    createdTime: "Yesterday at 10:30 PM",
    exposure: 32800,
    transactionsCount: 9,
    networkConnections: 4,
    riskScore: 61,
    summary:
      "4 consecutive wallet-to-wallet transfers just beneath the ৳25,000 threshold within a 45-minute window.",
    recommendation: "Continue enhanced monitoring for next 24 hours.",
    confidence: 78,
  },
  {
    id: "INV-1019",
    riskLevel: "Medium",
    customer: "U-7712",
    amount: 12800,
    reason: "Device anomaly & agent liquidity shift",
    analyst: "Rakib Hasan",
    status: "Pending Review",
    updated: "3 hrs ago",
    createdTime: "Yesterday at 07:15 PM",
    exposure: 45000,
    transactionsCount: 16,
    networkConnections: 5,
    riskScore: 58,
    summary:
      "Unusual cash-out concentration at Agent AG-3091 coinciding with high device failure rate.",
    recommendation: "Request agent verification photo and transaction receipt.",
    confidence: 74,
  },
  // Added Case
  {
    id: "INV-1055",
    riskLevel: "Critical",
    customer: "U-9182",
    amount: 98000,
    reason: "SIM Swap & Maximum Limit Drain",
    analyst: "Unassigned",
    status: "Investigating",
    updated: "Just now",
    createdTime: "Today at 03:46 AM",
    exposure: 98000,
    transactionsCount: 1,
    networkConnections: 2,
    riskScore: 98,
    summary: "Complete account drain detected following a carrier SIM swap event in Sylhet. High priority critical alert.",
    recommendation: "Freeze immediately. Reverse transaction and notify carrier.",
    confidence: 99,
  }
];

export const evidenceTimelineINV1042: TimelineEvent[] = [
  {
    time: "02:01 AM",
    title: "Device changed & session authenticated",
    description: "New Android device DEV-8821 (Samsung S23) logged in from IP 103.114.98.12 (Mirpur, Dhaka).",
  },
  {
    time: "02:05 AM",
    title: "Small probing transaction",
    description: "৳1,500 transferred to test wallet U-5521. Transaction succeeded without PIN friction.",
  },
  {
    time: "02:08 AM",
    title: "Rapid velocity transfers initiated",
    description: "3 outgoing transfers of ৳15,000 each in 180 seconds across two new recipients.",
  },
  {
    time: "02:13 AM",
    title: "Critical Transfer (৳48,500)",
    description: "High-value transfer to U-8831. Amount is 4.8× above normal 30-day baseline.",
    isCritical: true,
  },
  {
    time: "02:15 AM",
    title: "Graph network cluster match",
    description: "Recipient U-8831 detected as node in Suspicious Mule Cluster #17 (43 linked txns).",
    isCritical: true,
  },
  {
    time: "02:18 AM",
    title: "Sentinel AI Automated Case Escalation",
    description: "Risk engine generated INV-1042 with 94/100 risk score and 96% AI confidence.",
  },
];

export const customerU1042: CustomerProfile = {
  id: "U-1042",
  name: "Tanvir Ahmed",
  phone: "+880 1711-239481",
  riskLevel: "High",
  riskScore: 82,
  kycStatus: "Verified",
  accountAge: "3y 2m",
  totalVolume: 1420000,
  avgTransaction: 6800,
  knownDevices: ["DEV-2211 (iPhone 14)", "DEV-3012 (MacBook Pro)"],
  knownLocations: ["Gulshan, Dhaka", "Banani, Dhaka", "Dhanmondi, Dhaka"],
  typicalHours: "10:00 AM – 09:00 PM",
  recentDeviations: [
    {
      title: "New device login",
      value: "DEV-8821 registered at 02:01 AM",
      severity: "Critical",
      timestamp: "Today at 02:01 AM",
    },
    {
      title: "Spike in transaction amount",
      value: "৳48,500 (4.8× above normal average)",
      severity: "High",
      timestamp: "Today at 02:13 AM",
    },
    {
      title: "Unknown recipient target",
      value: "First-time transfer to U-8831",
      severity: "High",
      timestamp: "Today at 02:13 AM",
    },
  ],
};

export const networkNodes: NetworkNode[] = [
  { id: "U-1042", label: "U-1042", type: "customer", risk: "Critical", x: 190, y: 255, clusterId: 17, details: "Originating Victim/Compromised Wallet" },
  { id: "U-8831", label: "U-8831", type: "recipient", risk: "Critical", x: 380, y: 190, clusterId: 17, details: "Primary Mule Conduit" },
  { id: "U-4412", label: "U-4412", type: "recipient", risk: "Critical", x: 545, y: 265, clusterId: 17, details: "Secondary Consolidation Hub" },
  { id: "U-9288", label: "U-9288", type: "recipient", risk: "Critical", x: 700, y: 160, clusterId: 17, details: "Final Liquidation Wallet" },
  { id: "DEV-8821", label: "DEV-8821", type: "device", risk: "High", x: 460, y: 75, clusterId: 17, details: "Shared Device (Used across 3 accounts)" },
  { id: "U-5509", label: "U-5509", type: "recipient", risk: "High", x: 360, y: 365, clusterId: 17, details: "Linked Smurfing Inflow" },
  { id: "U-3018", label: "U-3018", type: "recipient", risk: "Critical", x: 680, y: 375, clusterId: 17, details: "Rapid Cash-out Conduit" },
  { id: "U-2198", label: "U-2198", type: "recipient", risk: "High", x: 720, y: 285, clusterId: 17, details: "Off-shore Remittance Relay" },
  { id: "U-7742", label: "U-7742", type: "customer", risk: "normal", x: 115, y: 105, details: "Normal Salaried P2P User" },
  { id: "U-8842", label: "U-8842", type: "customer", risk: "normal", x: 120, y: 415, details: "Regular Utility Payer" },
  { id: "M-291", label: "M-291 (Merchant)", type: "merchant", risk: "normal", x: 530, y: 430, details: "Supermarket POS Terminal" },
  { id: "U-1028", label: "U-1028", type: "customer", risk: "normal", x: 815, y: 75, details: "Legitimate Freelancer Account" },
  { id: "DEV-1074", label: "DEV-1074", type: "device", risk: "normal", x: 825, y: 390, details: "Authorized Mobile Terminal" },
  { id: "AG-3091", label: "AG-3091 (Agent)", type: "agent", risk: "High", x: 260, y: 410, clusterId: 17, details: "Suspicious High-Volume Cash-Out Agent" },
  // Expanded Network Nodes
  { id: "U-9901", label: "U-9901", type: "recipient", risk: "Critical", x: 200, y: 100, clusterId: 99, details: "Known Fraudster Hub" },
  { id: "U-9182", label: "U-9182", type: "customer", risk: "Critical", x: 250, y: 180, clusterId: 99, details: "Victim of SIM Swap" },
  { id: "DEV-9901", label: "DEV-9901", type: "device", risk: "Critical", x: 100, y: 150, clusterId: 99, details: "Rogue Device from Emulator" },
];

export const networkEdges: NetworkEdge[] = [
  { source: "U-1042", target: "U-8831", amount: 48500, isHot: true, type: "transfer" },
  { source: "U-8831", target: "U-4412", amount: 45000, isHot: true, type: "transfer" },
  { source: "U-4412", target: "U-9288", amount: 88000, isHot: true, type: "transfer" },
  { source: "DEV-8821", target: "U-8831", isHot: true, type: "shared_device" },
  { source: "DEV-8821", target: "U-1042", isHot: true, type: "shared_device" },
  { source: "U-8831", target: "U-5509", amount: 15000, type: "transfer" },
  { source: "U-4412", target: "U-3018", amount: 28000, isHot: true, type: "transfer" },
  { source: "U-4412", target: "U-2198", amount: 19500, type: "transfer" },
  { source: "U-1042", target: "U-7742", amount: 2500, type: "transfer" },
  { source: "U-1042", target: "U-8842", amount: 1400, type: "transfer" },
  { source: "U-5509", target: "M-291", amount: 4200, type: "transfer" },
  { source: "U-3018", target: "M-291", amount: 8900, type: "transfer" },
  { source: "U-9288", target: "U-1028", amount: 5000, type: "transfer" },
  { source: "U-2198", target: "DEV-1074", type: "shared_device" },
  { source: "U-1042", target: "AG-3091", amount: 30000, isHot: true, type: "agent_cashout" },
  // Expanded Network Edges
  { source: "U-9182", target: "U-9901", amount: 98000, isHot: true, type: "transfer" },
  { source: "DEV-9901", target: "U-9182", isHot: true, type: "shared_device" },
  { source: "DEV-9901", target: "U-9901", isHot: true, type: "shared_device" },
];

export const alertsList: AlertItem[] = [
  {
    id: "ALT-1048",
    severity: "Critical",
    title: "Possible coordinated mule activity",
    description: "17 connected wallets and ৳2.8M volume routed through newly active accounts.",
    timeAgo: "2 minutes ago",
    iconType: "network",
    confidence: 94,
    relatedId: "INV-1042",
    unread: true,
  },
  {
    id: "ALT-1049",
    severity: "Critical",
    title: "SIM Swap Fraud Vector Detected",
    description: "SIM swapped on customer U-9182 10 minutes prior to a full balance drain of ৳98,000.",
    timeAgo: "1 minute ago",
    iconType: "shield",
    confidence: 99,
    relatedId: "INV-1055",
    unread: true,
  },
  {
    id: "ALT-1047",
    severity: "High",
    title: "Account takeover pattern detected",
    description: "New device login followed by password change and full balance sweep on U-2214.",
    timeAgo: "8 minutes ago",
    iconType: "shield",
    confidence: 91,
    relatedId: "INV-1038",
    unread: true,
  },
  {
    id: "ALT-1046",
    severity: "Medium",
    title: "Abnormal transaction velocity burst",
    description: "12 micro-transfers executed within 10 minutes from single IP subnet.",
    timeAgo: "21 minutes ago",
    iconType: "activity",
    confidence: 85,
    relatedId: "INV-1028",
    unread: false,
  },
  {
    id: "ALT-1045",
    severity: "High",
    title: "Suspicious recipient cluster link",
    description: "Recipient wallet U-4412 has 4 confirmed scam complaints filed in the last 48h.",
    timeAgo: "34 minutes ago",
    iconType: "network",
    confidence: 88,
    relatedId: "INV-1031",
    unread: false,
  },
  {
    id: "ALT-1044",
    severity: "Medium",
    title: "Simulated Agent Cash-out Anomaly",
    description: "Agent AG-3091 processed ৳420,000 cash-out in 40 minutes with 90% new SIM cards.",
    timeAgo: "1 hour ago",
    iconType: "device",
    confidence: 79,
    relatedId: "INV-1019",
    unread: false,
  },
];

export const defaultChatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    sender: "analyst",
    text: "Why is transaction TXN-8F42 considered critical risk?",
    timestamp: "02:19 AM",
  },
  {
    id: "msg-2",
    sender: "ai",
    text: "This transaction received a risk score of 94/100 because five independent signals deviate severely from the customer's normal behavior: transaction amount (4.8× normal median), unverified device (DEV-8821), recipient relationship (U-8831 linked to Cluster #17), burst velocity (6 transfers / 8 min), and off-hours timing (02:13 AM).",
    timestamp: "02:19 AM",
    evidenceUsed: [
      "Customer 30-day baseline (৳6,800 avg)",
      "Device fingerprint history (DEV-8821 first seen)",
      "Transaction graph (1-hop from Cluster #17)",
      "Behavioral time distribution (0 historic 2 AM txns)",
    ],
    disclaimer: "AI recommendations support analyst decisions. High-impact actions require human verification.",
  },
];
